package py.com.sgipy.miesys.view;

import java.util.ArrayList;
import java.util.List;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;
import com.vaadin.ui.themes.ValoTheme;

import py.com.sgipy.miesys.MiesysUI;
import py.com.sgipy.miesys.util.UserUtil;
import py.com.sgipy.miesys.util.ViewConfig;






@ViewConfig(uri = "", displayName = "Principal")
public class PrincipalView extends CustomComponent implements View {
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout datosLayout;
	@AutoGenerated
	private HorizontalLayout botonLayout;
	@AutoGenerated
	private Button btn3;
	@AutoGenerated
	private Button btn2;
	@AutoGenerated
	private Button btn1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	private Button btn4 ;
	private Button btn5;
	private Button btn6;
	private Button btn7;
	private Button btn8;
	private Button btn9;
	private Button btn10;
	private Button btn11;
	private Button btn12;
	private Button btn13;
	private Button btn14;
	private Button btn15;
	private Button btn16;
	
	private Window ventana;
	
	private List<Button> listBtn = new ArrayList<Button>();
	
	public PrincipalView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		btn4 = new Button();
		btn5 = new Button();
		btn6 = new Button();
		btn7 = new Button();
		btn8 = new Button();
		btn9 = new Button();
		btn10 = new Button();
		btn11 = new Button();
		btn12 = new Button();
		btn13 = new Button();
		btn14 = new Button();
		btn15 = new Button();
		btn16 = new Button();
	
		//btn1.setCaption("Vacaciones");
		btn2.setCaption("Funcionarios");
		btn3.setCaption("Alta usuario");
		btn4.setCaption("Usuarios");
		btn5.setCaption("Alta Cargos");
		btn6.setCaption("Cargos");
		btn7.setCaption("Alta Area");
		//btn7.setCaption("Modificaciones de Departamento");*/
		btn8.setCaption("Area");
		btn9.setCaption("Alta de Grupos");
		btn10.setCaption("Grupos");
		btn11.setCaption("Asignar grupo de preguntas a cargo");
		btn12.setCaption("Alta Pregunta");
		btn13.setCaption("Asignar preguntas a Grupos.");
		btn14.setCaption("Evaluacion");
		btn15.setCaption("Asignar Evaluador a cargo");
		btn16.setCaption("Asignar Pregunta a Cargo");
		

		btn2.addStyleName(ValoTheme.BUTTON_DANGER);
		btn2.addClickListener(event -> MiesysUI.getCurrent().getNavigator().navigateTo("funcionario"));
		listBtn.add(btn2);
		
		btn3.addStyleName(ValoTheme.BUTTON_DANGER);
		btn3.addClickListener(event -> MiesysUI.getCurrent().getNavigator().navigateTo("altaUsuario"));
		listBtn.add(btn3);
		
		btn4.addClickListener(event -> MiesysUI.getCurrent().getNavigator().navigateTo("usuario"));
		btn4.addStyleName(ValoTheme.BUTTON_DANGER);
		
		//botonLayout.addComponent(btn4);
		
		btn5.addClickListener(event -> MiesysUI.getCurrent().getNavigator().navigateTo("altaCargo"));
		btn5.setStyleName(ValoTheme.BUTTON_DANGER);
		
		//botonLayout.addComponent(btn5);
	
			
		
		btn6.addClickListener(event -> MiesysUI.getCurrent().getNavigator().navigateTo("cargo"));
		btn6.setStyleName(ValoTheme.BUTTON_DANGER);
		listBtn.add(btn6);
		
		
		btn7.addClickListener(e -> MiesysUI.getCurrent().getNavigator().navigateTo("altaArea"));
		btn7.setStyleName(ValoTheme.BUTTON_DANGER);
		
		//botonLayout.addComponent(btn7);
		
		
		
		/*btn8.addClickListener(e -> EvaUI.getCurrent().getNavigator().navigateTo("area"));
		btn8.addStyleName(ValoTheme.BUTTON_DANGER);
		listBtn.add(btn8);
		
		
		btn9.addClickListener(e -> EvaUI.getCurrent().getNavigator().navigateTo("altaGrupo"));
		btn9.setStyleName(ValoTheme.BUTTON_DANGER);
		
		//botonLayout.addComponent(btn9);
		
		btn10.addClickListener(e -> EvaUI.getCurrent().getNavigator().navigateTo("grupo"));
		btn10.setStyleName(ValoTheme.BUTTON_DANGER);
		listBtn.add(btn10);
		
//		botonLayout.addComponent(btn10);
		
		btn11.addClickListener(e -> EvaUI.getCurrent().getNavigator().navigateTo("cargoGrupo"));
		btn11.setStyleName(ValoTheme.BUTTON_DANGER);
		
		//botonLayout.addComponent(btn11);
		
		btn12.addClickListener(e -> EvaUI.getCurrent().getNavigator().navigateTo("altaPregunta"));
		btn12.setStyleName(ValoTheme.BUTTON_DANGER);
		listBtn.add(btn12);*/
		
//		botonLayout = new HorizontalLayout();
		
//		datosLayout.addComponent(botonLayout);
		
		
		
//		botonLayout.addComponent(btn12);
		
		/*btn13.addClickListener(e -> EvaUI.getCurrent().getNavigator().navigateTo("grupoPregunta"));
		btn13.setStyleName(ValoTheme.BUTTON_DANGER);
		listBtn.add(btn13);
		
//		botonLayout.addComponent(btn13);
		
		btn14.addClickListener(e-> EvaUI.getCurrent().getNavigator().navigateTo("evaluacion"));
		btn14.setStyleName(ValoTheme.BUTTON_DANGER);
		listBtn.add(btn14);
		
//		botonLayout.addComponent(btn14);
		
		
		btn15.addClickListener(e -> EvaUI.getCurrent().getNavigator().navigateTo("evaluadorCargo"));
		btn15.setStyleName(ValoTheme.BUTTON_DANGER);
//		botonLayout.addComponent(btn15);
		listBtn.add(btn15);
		
		btn16.addClickListener(e -> EvaUI.getCurrent().getNavigator().navigateTo("cargoPregunta"));
		btn16.setStyleName(ValoTheme.BUTTON_DANGER);
//		botonLayout.addComponent(btn16);
		listBtn.add(btn16);
		
		botonLayout = new HorizontalLayout();
		botonLayout.setMargin(false);
		botonLayout.setSpacing(false);
//		botonLayout.setWidth("60%");*/
		if (UserUtil.getUsuario().getPerfil().getPerfil() == 1) {
			
			int cont = 0;
			
			for (Button btn : listBtn) {
				
				cont = cont + 1;
				
				botonLayout.addComponent(btn);
				
				if (cont % 4 == 0 ) {
					
					datosLayout.addComponent(botonLayout);
					datosLayout.setComponentAlignment(botonLayout, Alignment.MIDDLE_CENTER);
					botonLayout = new HorizontalLayout();
					botonLayout.setMargin(false);
					botonLayout.setSpacing(false);
//					botonLayout.setWidth("60%");
				}
				
			}
			
			datosLayout.addComponent(botonLayout);
			datosLayout.setComponentAlignment(botonLayout, Alignment.MIDDLE_CENTER);
			
		}else {
			//botonLayout.addComponent(btn14);
			datosLayout.removeAllComponents();
			datosLayout.addComponent(btn14);
		}
		
		
		
		
		
		//btn3.addClickListener(event -> addUsuario());
		
		//botonLayout.addComponents(btn4, btn5, btn6, btn7);
		
	}
/*	private void addUsuario() {
		
		AltaUsuarioView altaUsuario = new AltaUsuarioView();
		
		ventana = new Window("Alta Persona", altaUsuario);
		ventana.center();
		ventana.setSizeFull();
		UI.getCurrent().addWindow(ventana);
		
		
	}*/
	@Override
	public void enter(ViewChangeEvent event) {
		// TODO Auto-generated method stub
		
	}
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		//mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// datosLayout
		datosLayout = buildDatosLayout();
		mainLayout.addComponent(datosLayout);
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildDatosLayout() {
		// common part: create layout
		datosLayout = new VerticalLayout();
		//datosLayout.setImmediate(false);
		datosLayout.setWidth("100.0%");
		datosLayout.setHeight("100.0%");
		datosLayout.setMargin(false);
		
		// botonLayout
		botonLayout = buildBotonLayout();
		datosLayout.addComponent(botonLayout);
		datosLayout.setComponentAlignment(botonLayout, new Alignment(48));
		
		return datosLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildBotonLayout() {
		// common part: create layout
		botonLayout = new HorizontalLayout();
		//botonLayout.setImmediate(false);
		botonLayout.setWidth("-1px");
		botonLayout.setHeight("-1px");
		botonLayout.setMargin(false);
		
		// btn1
		btn1 = new Button();
		btn1.setCaption("Button");
		//btn1.setImmediate(true);
		btn1.setWidth("-1px");
		btn1.setHeight("-1px");
		//botonLayout.addComponent(btn1);
		
		// btn2
		btn2 = new Button();
		btn2.setCaption("Button");
		//btn2.setImmediate(true);
		btn2.setWidth("-1px");
		btn2.setHeight("-1px");
		botonLayout.addComponent(btn2);
		
		// btn3
		btn3 = new Button();
		btn3.setCaption("Button");
		//btn3.setImmediate(true);
		btn3.setWidth("-1px");
		btn3.setHeight("-1px");
		botonLayout.addComponent(btn3);
		
		return botonLayout;
	}
	
	
	
	
	
	
	
	

}
